name    = "StableRNGs"
uuid    = "860ef19b-820b-49d6-a774-d7a799459cd3"
authors = ["Rafael Fourquet <fourquet.rafael@gmail.com>"]
version = "1.0.2"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Random = "<0.0.1, 1"
Test = "<0.0.1, 1"
julia = "1"

[extras]
Test   = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
